---
- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Copy zfsnap script on server
  copy: 
    src: "zfSnap.sh"
    dest: "/usr/local/sbin/zfsnap.sh"
    owner: "root"
    group: "root"
    mode: "0700" 
  when: ansible_os_family == "RedHat"

- name: Ensure zfsnap is installed
  apt: 
    name: 
      - "zfsnap"
    state: present
  when: ansible_os_family == "Debian"

- name: Create cron task for incremental backups
  cron: 
    minute: 0 
    hour: 0
    user: "root"
    name: "Create backups"
    cron_file: "zfsnap"
    job: "{{ zfsnap_name }} -a {{ zfsnap_backup_expiry }} -r {{ item }}"
    backup: yes
    state: present
  loop: "{{ zfsnap_pools }}"

- name: Create cron task for deleting old backups
  cron: 
    minute: 0 
    hour: 1 
    user: "root"
    name: "Delete backups"
    cron_file: "zfsnap_delete"
    job: "{{ zfsnap_name }} -d"
    backup: yes
    state: present

