---
- name: Load the OS specific variables
  tags: zfsnap
  include_vars: "{{ ansible_os_family }}.yml"

- name: Copy zfsnap script on server
  tags: zfsnap
  copy: src=zfSnap.sh dest=/usr/local/sbin/zfsnap.sh owner=root group=root mode=0700

- name: Create cron task for incremental backups
  tags: zfsnap
  cron:
    minute: "{{ item.minute|default('23') }}"
    hour: "{{ item.hour|default('01') }}"
    day: "{{ item.day|default('*') }}"
    month: "{{ item.month|default('*') }}"
    dow: "{{ item.dow|default('*') }}"
    user: "{{ item.user|default(user) }}"
    name: "{{ item.cron_file|default(cron_file) }}"
    cron_file: "{{ item.cron_file|default(cron_file) }}"
    job: "/usr/local/sbin/zfsnap.sh -a {{ item.ttl|default('1m') }} -r {{ item.backup_path|default('tank/vz') }}"
    backup: yes
    state: present
  with_items: "{{ zfsnap_jobs }}"

- name: Create cron task for deleting old backups
  tags: zfsnap
  cron:
    minute: 0
    hour: 1
    user: "{{ user }}"
    name: "Delete backups"
    cron_file: "zfsnap_delete"
    job: "/usr/local/sbin/zfsnap.sh -d"
    backup: yes
    state: present
